# 配置端口
server:
  port: 9108
  servlet:
    #    context-path: /api
    application-display-name: demo
swagger:
  enable: true
  basePackage: com.wqy
  groupName: api接口管理
  version: @project.version@
spring:
  application:
      name: demo
  profiles:
    active: dev