
ownerException:
  front: #前端提示
    W001: 请求中%s数据异常
    W002: 请求中%s数据异常
    W003: 权限不足，越权操作
    W004: 用户不存在
    W005: 系统故障，请联系管理员
  back: #后端提示
    W001: 数据中的[%s],含有[%s]异常信息
    W002: 数据中的[%s],含有[%s]异常信息
    W003: 权限不足，越权操作
    W004: 用户不存在
    W005: 系统故障，[%s]